### ISSUE TITLE
Relax ToWkt impls to work with CoordNum

### ISSUE THREAD

**Issue by rmanoka** [georust/wkt#100]
Currently the `ToWkt` impls. need `T: CoordFloat + Display` on the geometry.  Can this be relaxed to `T: CoordNum + Display`?  Or, is this a big structural change?  Ideally, even `FromWkt` should rather use `CoordNum + FromStr` than `CoordFloat` if that's possible.

**Comment by michaelkirk** [comment]
I think it should be possible! It'll require some changes to the underlying Wkt type which is [currently restricted to num_traits::Float](https://github.com/georust/wkt/blob/main/src/lib.rs#L207) - but I can't imagine why it'd actually be relying on Float behavior for anything.

I can take a look tomorrow.
