### ISSUE TITLE
Use generic type for precision

### ISSUE THREAD

**Issue by frewsxcv** [georust/wkt#33]
http://rust-num.github.io/num/num_traits/float/trait.Float.html

**Comment by pjsier** [comment]
I'm interested in taking this on, it looks like the implementation would be the similar to [geojson](https://github.com/georust/geojson/blob/master/src/conversion.rs)?

**Comment by frewsxcv** [comment]
Yep, exactly! Pull in num-traits as a dependency, and use `num_traits::Float` everyewhere
