### ISSUE TITLE
Should we support LINEARRING type?

### ISSUE THREAD

**Issue by michaelkirk** [georust/wkt#50]
e.g. `LINEARRING(0 0, 0 5, 5 5, 5 0, 0 0)`

JTS uses this - but it's unclear to me if this is a standard thing that we would benefit from supporting.

**Comment by frewsxcv** [comment]
https://geos.osgeo.org/doxygen/classgeos_1_1io_1_1WKTWriter.html

GEOS also uses it apparently

> A non-standard "LINEARRING" tag is used for LinearRings. The WKT spec does not define a special tag for LinearRings. The standard tag to use is "LINESTRING".

Not sure! My initial feeling is `LINEARRING` could be behind a feature flag? Though I'd love to hear how commonly it gets used, though not sure how to do that

**Comment by rmanoka** [comment]
For comparison: openlayers seems to have considered this a while back (https://github.com/openlayers/openlayers/issues/2679).  IIUC, they did not support it!  However, given JTS, geos and shapely output it, it would be good to support it behind a feature flag.

**Comment by rmanoka** [comment]
Along the same lines as this issue:  JTS, geos, shapely also seem to support nan, inf, etc. in WKT.  They have an "is_valid" predicate that'll be false, but allow conversion to / from wkt with nans.   Eg. `POINT (nan  0.0)` or `POINT (10 inf)`

**Comment by michaelkirk** [comment]
> it would be good to support it behind a feature flag

That sounds like a smart approach to me.

**Comment by rmanoka** [comment]
Should we support `LINEARRING` as another enum-case to the `Geometry` type here?  Then, convert to `LineString` in the conversion to geo-types?

**Comment by lnicola** [comment]
Feature-gated enum values are a bit weird. Take this example:

 - program P uses crates C1 and C2
 - crates C1 and C2 use `wkt`
 - crate C2 enables the `linearring` feature
 - crate C1 stops building because it's no longer exhaustively a `wkt::Geometry` value

C1 _could_ prevent this by adding fallback `match` branches. Alternatively, `wkt` could mark `Geometry` as `non_exhaustive` to force dependent crates to use a fallback when matching against it. But neither solution seems ideal.

**Comment by rmanoka** [comment]
Nice catch @lnicola ; I am also convinced against feature-gated addition to the enums.  Should we then store the name of the tag in addition for this variant?  We could also silently convert it to a linestring, but then parsing and writing back changes the wkt.

**Comment by lnicola** [comment]
We could also have a variant for it and a normalization method, but I'd go for silently covering them until a user asks for more support.

**Comment by michaelkirk** [comment]
To make sure I understand: by "silently convert", do you mean that _any_ linestring which is `closed` will be serialized to WKT as `LINEARRING?`

Would that behavior be behind a feature flag?

**Comment by lnicola** [comment]
I meant reading LINEARRING as LineString. It changes the WKT if you read and write back a file, but maybe it won't bother anyone.

**Comment by rmanoka** [comment]
Any further thoughts on this?  I like the idea of silently reading LINEARRING and converting to LineString.   Adding support for shapely and JTS extensions seems like a win for good interop.

**Comment by michaelkirk** [comment]
I support it!

**Comment by michaelkirk** [comment]
Fixed in #67 

We might choose to do more in the future, but let's see what people's actual use cases are when they come up.
