### ISSUE TITLE
Publish WKT 0.9.0

### ISSUE THREAD

**Issue by michaelkirk** [georust/wkt#58]
There's a nice bundle of changes ready to go out. Note, this would be a breaking release, due to the geo-types 0.7.0 requirement.

Anything else people would want to see in the 0.9.0 release?

I just checked [the diff since 0.8.0](https://github.com/georust/wkt/compare/0.8.0...master) and it looks like CHANGES.md is up to date.

(I'd be happy to publish the release myself if @frewsxcv adds me to https://github.com/orgs/georust/teams/wkt-publishers)

**Comment by frewsxcv** [comment]
Added you to the team!

**Comment by michaelkirk** [comment]
Excellent thanks! 

I'm inferring that you're also OK with the release as-is and will get it out shortly.

**Comment by frewsxcv** [comment]
Yep yep. Was on my phone when I gave you permissions and was dancing around the GitHub permissions UI and then forgot to response with a 👍🏻 here

**Comment by michaelkirk** [comment]
WKT 0.9.0 has been published!
