### ISSUE TITLE
Make geo-types a non-optional dependency

### ISSUE THREAD

**Issue by urschrei** [georust/wkt#74]
As part of #71 I've written some examples. However, the most simple "practical" example uses `geo-types`, which is enabled by default, but optional, which means we can't run `--no-default-features` in tests (The use of unstable nightly features notwithstanding).

Is there a reason to keep `geo-types` as an optional feature? Are there existing uses cases which don't make use of `geo-types`? Is it likely that potential users of the crate will be put off by a dependency on `geo-types`?

**Comment by lnicola** [comment]
I'm quite in favour of this. I'm generally worried about compile times, but `geo-types` isn't _that_ bad:

![image](https://user-images.githubusercontent.com/308347/150534474-77aef95d-3e80-485b-ab2c-7ebbab0fccdf.png)

**Comment by urschrei** [comment]
Keeping it optional for now!
