### ISSUE TITLE
make Wkt<T> display

### ISSUE THREAD

**Issue by queer-emma** [georust/wkt#83]
I was trying to find out how to get a Wkt to actually convert to a string. Is there a reason why it doesn't implement `Display`? It seems, instead i have to do `ẁkt.item.to_string()` - which I find counter-intuitive.

**Comment by lnicola** [comment]
Until recently, a single `Wkt` values could represent multiple geometries, which would have posed some problems when implementing `ToString`. But adding it now seems quite reasonable.

**Comment by queer-emma** [comment]
This makes sense now. I just couldn't figure out why the README says that you can encode WKT strings, but there is no method for it. I didn't see that the individual types are `Display`, and i also just wanted to encode the `Wkt<_>`.

**Comment by michaelkirk** [comment]
Fixed by @categulario in https://github.com/georust/wkt/pull/86
